### ISSUE TITLE
Overlapping Card container

### ISSUE THREAD

**Issue by Lekanjoy** [doriandevtech/TheCryptoApp#2]
## The crypto cards container seems to overlap the sidebar in desktop mode
![issue1](https://user-images.githubusercontent.com/90498638/184721803-a9485843-7187-4aa6-9812-c5b0ab1fd5e7.jpg)

**Comment by doriandevtech** [comment]
@Lekanjoy I added a little change with a PR, what do you think ?

**Comment by Lekanjoy** [comment]
@doriandevtech Looks good now. Great work
